
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr 16 2026 12:29:51 IST (Apr 16 2026 06:59:51 UTC)

// Verification Directory fv/barrel_shifter_4bit 

module barrel_shifter_4bit(clk, rst_n, data_in, shift_amt, data_out,
     scan_en, scan_in, scan_out);
  input clk, rst_n, scan_en, scan_in;
  input [3:0] data_in;
  input [1:0] shift_amt;
  output [3:0] data_out;
  output scan_out;
  wire clk, rst_n, scan_en, scan_in;
  wire [3:0] data_in;
  wire [1:0] shift_amt;
  wire [3:0] data_out;
  wire scan_out;
  wire [3:0] stage1;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  SDFFRHQX1 \data_out_reg[2] (.RN (rst_n), .CK (clk), .D (n_8), .SI
       (data_out[1]), .SE (scan_en), .Q (data_out[2]));
  SDFFRHQX1 \data_out_reg[3] (.RN (rst_n), .CK (clk), .D (n_9), .SI
       (data_out[2]), .SE (scan_en), .Q (data_out[3]));
  SDFFRHQX1 \data_out_reg[0] (.RN (rst_n), .CK (clk), .D (n_10), .SI
       (scan_in), .SE (scan_en), .Q (data_out[0]));
  SDFFRHQX1 \data_out_reg[1] (.RN (rst_n), .CK (clk), .D (n_11), .SI
       (data_out[0]), .SE (scan_en), .Q (data_out[1]));
  SDFFRHQX1 \stage1_reg[3] (.RN (rst_n), .CK (clk), .D (n_12), .SI
       (stage1[2]), .SE (scan_en), .Q (scan_out));
  SDFFRHQX1 \stage1_reg[2] (.RN (rst_n), .CK (clk), .D (n_13), .SI
       (stage1[1]), .SE (scan_en), .Q (stage1[2]));
  SDFFRHQX1 \stage1_reg[0] (.RN (rst_n), .CK (clk), .D (n_14), .SI
       (data_out[3]), .SE (scan_en), .Q (stage1[0]));
  SDFFRHQX1 \stage1_reg[1] (.RN (rst_n), .CK (clk), .D (n_15), .SI
       (stage1[0]), .SE (scan_en), .Q (stage1[1]));
  MX2XL g19(.A (stage1[2]), .B (stage1[0]), .S0 (shift_amt[1]), .Y
       (n_8));
  MX2XL g227(.A (scan_out), .B (stage1[1]), .S0 (shift_amt[1]), .Y
       (n_9));
  MX2XL g228(.A (stage1[0]), .B (stage1[2]), .S0 (shift_amt[1]), .Y
       (n_10));
  MX2XL g229(.A (stage1[1]), .B (scan_out), .S0 (shift_amt[1]), .Y
       (n_11));
  MX2XL g230(.A (data_in[3]), .B (data_in[2]), .S0 (shift_amt[0]), .Y
       (n_12));
  MX2XL g231(.A (data_in[2]), .B (data_in[1]), .S0 (shift_amt[0]), .Y
       (n_13));
  MX2XL g232(.A (data_in[0]), .B (data_in[3]), .S0 (shift_amt[0]), .Y
       (n_14));
  MX2XL g233(.A (data_in[1]), .B (data_in[0]), .S0 (shift_amt[0]), .Y
       (n_15));
endmodule

