#=============================================================================
# Modus ATPG Script
# Design  : barrel_shifter_4bit
# Tool    : Cadence Modus Test Solution
# Mode    : FULLSCAN  (all 8 FFs are scan-FFs in a single chain)
#
# Pre-requisites (generated by run_genus_dft.tcl):
#   barrel_shifter_4bit_post_dft.v   – post-DFT gate-level netlist
#   *.pinassign                       – port-to-signal assignments
#   *.modedef                         – test-mode definition
#=============================================================================

puts "\n============================================="
puts " Modus ATPG Script  :  barrel_shifter_4bit"
puts "============================================="

#-----------------------------------------------------------------------------
# Global Variables
#-----------------------------------------------------------------------------
set WORKDIR    ./
set CELL       barrel_shifter_4bit
set RESULTS_DIR ${WORKDIR}/results
set NETLIST    ${WORKDIR}/barrel_shifter_4bit_post_dft.v
set TESTMODE   FULLSCAN

#-----------------------------------------------------------------------------
# Create results directory
#-----------------------------------------------------------------------------
puts "\n>>> Creating results directory: $RESULTS_DIR"
file mkdir $RESULTS_DIR

#-----------------------------------------------------------------------------
# Locate 90nm technology library Verilog models (gate-level simulation models)
#-----------------------------------------------------------------------------
puts "\n>>> Locating technology library..."
set LIBRARY ""
catch {
    set raw_files [exec bash -c \
        "find /home/install/FOUNDRY/digital/90nm/dig/ \
              -type f | grep -E '\\.v$|\\.v\\.gz$|\\.V$'"]
    set LIBRARY [split $raw_files "\n"]
}
if {$LIBRARY eq ""} {
    puts "WARNING: Technology library not found. Check FOUNDRY path."
} else {
    puts "Found library files: $LIBRARY"
}

#-----------------------------------------------------------------------------
# Dynamically locate .pinassign and .modedef written by Genus
#-----------------------------------------------------------------------------
set ASSIGNFILE ""
set MODEDEF    ""
catch {
    set ASSIGNFILE [exec bash -c \
        "find $WORKDIR -maxdepth 1 -type f -name '*.pinassign' | head -n 1"]
    set MODEDEF    [exec bash -c \
        "find $WORKDIR -maxdepth 1 -type f -name '*.modedef'   | head -n 1"]
}
puts "Pin assignment file : $ASSIGNFILE"
puts "Mode definition file: $MODEDEF"

#-----------------------------------------------------------------------------
# Processing switches  (1 = run, 0 = skip)
#-----------------------------------------------------------------------------
set do_build_model                        1
set do_build_testmode_FULLSCAN            1
set do_report_test_structures_FULLSCAN    1
set do_verify_test_structures_FULLSCAN    1
set do_fault_model                        1
set do_create_atpg_vectors                1

#=============================================================================
# 1. BUILD MODEL
#    Reads the post-DFT netlist and the tech library to construct an internal
#    simulation model of barrel_shifter_4bit.
#=============================================================================
if {$do_build_model} {
    puts "\n>>> Building test model for $CELL ..."
    build_model \
        -cell               $CELL          \
        -workdir            $WORKDIR       \
        -designsource       $NETLIST       \
        -TECHLIB            $LIBRARY       \
        -allowmissingmodules yes
}

#=============================================================================
# 2. BUILD TEST MODE – FULLSCAN
#    Applies the scan protocol (scan_en, scan_in, scan_out, clk) from the
#    .modedef and .pinassign files so Modus knows how to drive the 8-FF chain.
#=============================================================================
if {$do_build_testmode_FULLSCAN} {
    puts "\n>>> Building test mode: $TESTMODE ..."
    if {$MODEDEF ne ""} {
        build_testmode \
            -workdir  $WORKDIR    \
            -testmode $TESTMODE   \
            -modedef  $MODEDEF    \
            -assignfile $ASSIGNFILE
    } else {
        # Fall back: no modedef (Modus infers from netlist scan annotations)
        build_testmode \
            -workdir    $WORKDIR    \
            -testmode   $TESTMODE   \
            -assignfile $ASSIGNFILE
    }
}

#=============================================================================
# 3. REPORT TEST STRUCTURES  (FULLSCAN)
#    Prints the number of scan chains, chain lengths, scan ports, etc.
#    For barrel_shifter_4bit you expect:
#       1 chain  |  8 scan-FFs  |  SI=scan_in  SO=scan_out  SE=scan_en
#=============================================================================
if {$do_report_test_structures_FULLSCAN} {
    puts "\n>>> Reporting test structures for $TESTMODE ..."
    report_test_structures \
        -workdir  $WORKDIR  \
        -testmode $TESTMODE \
        > $RESULTS_DIR/test_structures.rpt
}

#=============================================================================
# 4. VERIFY TEST STRUCTURES  (FULLSCAN)
#    Checks that all scan-FFs are reachable, chain lengths match, and
#    combinational controllability/observability is acceptable.
#=============================================================================
if {$do_verify_test_structures_FULLSCAN} {
    puts "\n>>> Verifying test structures for $TESTMODE ..."
    verify_test_structures \
        -workdir  $WORKDIR  \
        -testmode $TESTMODE \
        > $RESULTS_DIR/verify_structures.rpt
}

#=============================================================================
# 5. BUILD FAULT MODEL
#    Default: Stuck-At Fault (SAF) model.
#    With 8 FFs + combinational logic the fault universe is small; expect
#    high coverage (>95%) from a fully-stuck-at ATPG run.
#=============================================================================
if {$do_fault_model} {
    puts "\n>>> Building stuck-at fault model..."
    build_faultmodel
}

#=============================================================================
# 6. CREATE ATPG VECTORS & GENERATE REPORTS
#    create_logic_tests runs automatic ATPG to detect all modelled faults.
#    Results are saved in the 'ex1' experiment folder.
#=============================================================================
if {$do_create_atpg_vectors} {
    puts "\n>>> Generating ATPG test vectors (experiment: ex1)..."
    create_logic_tests \
        -experiment ex1     \
        -testmode   $TESTMODE

    # ------------------------------------------------------------------
    # Coverage statistics (detected / undetected / ATPG-untestable faults)
    # ------------------------------------------------------------------
    puts "\n>>> Writing fault coverage report..."
    report_statistics \
        -experiment ex1 \
        > $RESULTS_DIR/test_coverage.rpt

    # ------------------------------------------------------------------
    # Full fault list (detected / possibly-detected / undetected)
    # ------------------------------------------------------------------
    puts "\n>>> Writing fault list..."
    write_faults \
        -experiment     ex1                      \
        -all                                     \
        -outputfilename $RESULTS_DIR/fault_list.rpt

    # ------------------------------------------------------------------
    # Verilog test-bench vectors for gate-level simulation verification
    # ------------------------------------------------------------------
    puts "\n>>> Writing Verilog test vectors..."
    write_vectors \
        -inexperiment   ex1                         \
        -testmode       $TESTMODE                   \
        -language       verilog                     \
        -outputfilename $RESULTS_DIR/test_vectors.v
}

puts "\n============================================="
puts " Modus ATPG Complete!  barrel_shifter_4bit"
puts ""
puts " KEY OUTPUT FILES (in $RESULTS_DIR/):"
puts "   test_structures.rpt   – scan chain summary"
puts "   verify_structures.rpt – structural DRC"
puts "   test_coverage.rpt     – fault coverage %"
puts "   fault_list.rpt        – per-fault status"
puts "   test_vectors.v        – Verilog ATPG vectors"
puts "============================================="